# Streamlit Secrets Configuration
# Copy this to your Streamlit Cloud secrets section

[general]
SECRET_KEY = "your_super_secret_key_here_minimum_32_characters_long"
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

[database]
DATABASE_URL = "sqlite:///./data/alumni_club.db"

[email]
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USE_TLS = true
EMAIL_USER = "your_email@gmail.com"
EMAIL_PASSWORD = "your_app_password"
EMAIL_FROM_NAME = "Alumni Club Connect"

[settings]
CERTIFICATE_HOURS_THRESHOLD = 300
AUTO_SEND_CERTIFICATES = true
MAX_FILE_SIZE_MB = 10
